# docker-compose.yml
version: "3"
services:
  app:
    build: .
    ports:
      - "8088:8010"
    volumes:
      - ./src:/app/src
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    runtime: nvidia
